name: Deploy

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    # установка ключа
    - run: |
        set -eu
        mkdir "$HOME/.ssh"
        echo "${{ secrets.key }}" > "$HOME/.ssh/key"
        chmod 600 "$HOME/.ssh/key"
        
    # установка зависимостей 
    - run: |
        composer update --ignore-platform-req=php+ -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        npm ci
    
    # замена переменных окружения
    - run: |
        cp .env.example .env
        php artisan key:generate
        sed -i "s/DB_HOST=127.0.0.1/DB_CONNECTION=${{ secrets.db_host }}/" .env
        sed -i "s/DB_DATABASE=laravel/DB_CONNECTION=${{ secrets.db_name }}/" .env
        sed -i "s/DB_USERNAME=laravel/DB_CONNECTION=${{ secrets.db_login }}/" .env
        sed -i "s/DB_PASSWORD=laravel/DB_CONNECTION=${{ secrets.db_password }}/" .env
        
    # синхронизация файлов с хостингом
    - run: rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . "${{ secrets.login }}@${{ secrets.host }}:${{ secrets.path_site }}" --exclude node_modules/
